import { SymbolData } from "../types/symbol";

export const mockSymbols: SymbolData[] = [
  {
    symbol: "AAPL",
    description: "<em>APPLE</em> INC",
    type: "stock",
    exchange: "NASDAQ",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "AMAT",
    description: "<em>APPLIED</em> MATERIALS INC",
    type: "stock",
    exchange: "NASDAQ",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "4336",
    description: "<em>APPL</em> MATERIAL-T",
    type: "stock",
    exchange: "HKEX",
    provider_id: "ice",
    typespecs: ["common"],
    country: "HK",
  },
  {
    symbol: "APP",
    description: "<em>APPLOVIN</em> CORP",
    type: "stock",
    exchange: "NASDAQ",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "AGTC",
    description: "<em>APPLIED</em> GENETIC TECHNOLOGIES CORP",
    type: "stock",
    exchange: "NASDAQ",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "AAOI",
    description: "<em>APPLIED</em> OPTOELECTRONICS INC",
    type: "stock",
    exchange: "NASDAQ",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "AUVI",
    description: "<em>APPLIED</em> UV INC",
    type: "stock",
    exchange: "NASDAQ",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "APDN",
    description: "<em>APPLIED</em> DNA SCIENCES INC",
    type: "stock",
    exchange: "NASDAQ",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "AMTI",
    description: "<em>APPLIED</em> MOLECULAR TRANSPORT INC",
    type: "stock",
    exchange: "NASDAQ",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "APLT",
    description: "<em>APPLIED</em> THERAPEUTICS INC",
    type: "stock",
    exchange: "NASDAQ",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "APLE",
    description: "<em>APPLE</em> HOSPITALITY REIT INC",
    type: "stock",
    exchange: "NYSE",
    provider_id: "ice",
    typespecs: ["reit"],
    country: "US",
  },
  {
    symbol: "SAIC",
    description: "SCIENCE <em>APPLICATION</em> INTL CORP",
    type: "stock",
    exchange: "NYSE",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "AIT",
    description: "<em>APPLIED</em> INDUSTRIAL TECHNOLOGIES INC",
    type: "stock",
    exchange: "NYSE",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "GCP",
    description: "GCP <em>APPLIED</em> TECHNOLOGIES INC",
    type: "stock",
    exchange: "NYSE",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "002959",
    description: "BEAR ELECTRIC <em>APPL</em>",
    type: "stock",
    exchange: "SZSE",
    provider_id: "ice",
    typespecs: ["common"],
    country: "CN",
  },
  {
    symbol: "002025",
    description: "GUIZHOU SPACE <em>APPL</em>",
    type: "stock",
    exchange: "SZSE",
    provider_id: "ice",
    typespecs: ["common"],
    country: "CN",
  },
  {
    symbol: "AAPL-RM",
    description: "<em>APPL</em>E INC",
    type: "stock",
    exchange: "MOEX",
    provider_id: "ice",
    typespecs: ["common"],
    country: "RU",
  },
  {
    symbol: "AAPL",
    description: "<em>Appl</em>e",
    type: "stock",
    exchange: "CAPITALCOM",
    provider_id: "capitalcom",
    typespecs: ["cfd"],
  },
  {
    symbol: "AAPL",
    description: "<em>APPL</em>E INC",
    type: "stock",
    exchange: "BYMA",
    provider_id: "ice",
    country: "AR",
    prefix: "BCBA",
  },
  {
    symbol: "APC",
    description: "<em>APPL</em>E INC.",
    type: "stock",
    exchange: "XETR",
    provider_id: "ice",
    typespecs: ["common"],
    country: "DE",
  },
  {
    symbol: "AAPL34",
    description: "<em>APPL</em>E DRN",
    type: "stock",
    exchange: "BMFBOVESPA",
    provider_id: "ice",
    country: "BR",
  },
  {
    symbol: "AAPL",
    description: "<em>APPL</em>E",
    type: "stock",
    exchange: "MIL",
    provider_id: "ice",
    typespecs: ["common"],
    country: "IT",
  },
  {
    symbol: "APLD",
    description: "<em>APPLIED</em> SCIENCE PRODUCTS, INC.",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "APC",
    description: "<em>APPL</em>E INC. REGISTERED SHARES O.N.",
    type: "stock",
    exchange: "SWB",
    provider_id: "ice",
    typespecs: ["common"],
    country: "DE",
  },
  {
    symbol: "AAPL",
    description: "<em>APPL</em>E INC",
    type: "stock",
    exchange: "BMV",
    provider_id: "ice",
    typespecs: ["common"],
    country: "MX",
  },
  {
    symbol: "AFW",
    description: "<em>APPLYFLOW</em> LIMITED",
    type: "stock",
    exchange: "ASX",
    provider_id: "ice",
    typespecs: ["common"],
    country: "AU",
  },
  {
    symbol: "APQT",
    description: "<em>APPLIQATE</em> INC.",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "AMAT-RM",
    description: "<em>APPL</em>IED MATERIALS, INC",
    type: "stock",
    exchange: "MOEX",
    provider_id: "ice",
    typespecs: ["common"],
    country: "RU",
  },
  {
    symbol: "48T",
    description: "<em>APPL</em>E HOSPITALITY REIT",
    type: "stock",
    exchange: "SWB",
    provider_id: "ice",
    typespecs: ["reit"],
    country: "DE",
  },
  {
    symbol: "2UV",
    description: "<em>APPL</em>IED THERAPEUTDL-,0001",
    type: "stock",
    exchange: "SWB",
    provider_id: "ice",
    typespecs: ["common"],
    country: "DE",
  },
  {
    symbol: "UDJP",
    description: "<em>APPL</em>IED DNA DL-,0001",
    type: "stock",
    exchange: "SWB",
    provider_id: "ice",
    typespecs: ["common"],
    country: "DE",
  },
  {
    symbol: "APRU",
    description: "<em>APPLE</em> RUSH CO., INC.",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "APGMF",
    description: "<em>APPLIED</em> GRAPHENE MATERIALS PLC",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "FUAPF",
    description: "GLOBAL CANNABIS <em>APPLICATIONS</em> CORP",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "AMNL",
    description: "<em>APPLIED</em> MINERALS, INC.",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "AERG",
    description: "<em>APPLIED</em> ENERGETICS, INC.",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "APPB",
    description: "<em>APPLIED</em> BIOSCIENCES CORP",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "IOBCF",
    description: "ION BEAM <em>APPLICATIONS</em> S.A.",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "ALDS",
    description: "<em>APPLIFE</em> DIGITAL SOLUTIONS, INC.",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "BLVDF",
    description: "HELIX <em>APPLICATIONS</em> INC",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "AGPL",
    description: "<em>APPLE</em> GREEN HOLDING, INC.",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "CXIA",
    description: "COMMODORE <em>APPLIED</em> TECHNOLOGY",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "IGAP",
    description: "INTEGRITY <em>APPLICATIONS</em> INCORPORATION",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "APLUF",
    description: "<em>APPLUS</em> SVCS S A",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "APPDW",
    description: "<em>APPLIED</em> DNA SCIENCES, INC.",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    country: "US",
  },
  {
    symbol: "APVS",
    description: "<em>APPLIED</em> VISUAL SCIENCES, INC.",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "ADHLF",
    description: "<em>APPLIED</em> DEVELOPMENT HOLDINGS LIMITE",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "<em>APPL</em>ECREDT",
    description: "<em>APPL</em>E CREDIT CORPORATION LTD.",
    type: "stock",
    exchange: "BSE",
    provider_id: "ice",
    typespecs: ["common"],
    country: "IN",
  },
  {
    symbol: "UATG",
    description: "UMBRA <em>APPLIED</em> TECHNOLOGIES GROUP, INC.",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
  {
    symbol: "SINC",
    description: "SINCERITY <em>APPLIED</em> MATERIALS HOLDINGS CORP.",
    type: "stock",
    exchange: "OTC",
    provider_id: "ice",
    typespecs: ["common"],
    country: "US",
  },
];
